package com.chaoliu.utils;

public class Consts {

    public static final String KEY_MODULE_NAME="module";
    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY CHENTONG.\n";
    static final String PREFIX_OF_LOGGER = "chentong" + "::Compiler ";
    public static final String NO_MODULE_NAME_TIPS = "These no module name, at 'build.gradle', like :\n" +
            "android {\n" +
            "    defaultConfig {\n" +
            "        ...\n" +
            "        javaCompileOptions {\n" +
            "            annotationProcessorOptions {\n" +
            "                arguments = [module: project.getName()]\n" +
            "            }\n" +
            "        }\n" +
            "    }\n" +
            "}\n";

    // System interface
    public static final String ACTIVITY = "android.app.Activity";
    public static final String FRAGMENT = "android.app.Fragment";
    public static final String FRAGMENT_V4 = "android.support.v4.app.Fragment";
    public static final String VIEW = "android.view.View";

    // Custom interface
    private static final String API_PACKAGE = "com.chaoliu.api";
    private static final String TEMPLATE_PACKAGE = ".templete";
    public static final String UNBINDER = API_PACKAGE + TEMPLATE_PACKAGE + ".Unbinder";

    public static final String SUFFIX = "_ViewBinding";

}